apiVersion: v2
name: vllm-stack
description: Qwen 3.8B + LiteLLM on Huawei Ascend 910B NPUs
type: application
version: 0.1.0
appVersion: "1.0"

keywords:
  - vllm
  - ascend
  - qwen
  - litellm

maintainers:
  - name: llm-deplyoment